import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import NavBar from "@/shared/navigation/NavBar";
import Footer from "@/shared/navigation/Footer";
import { navbar_data } from "@/data/navigation-data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <NavBar data={navbar_data} />
                    {children}
                    <Footer />
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
